### Get Users
GET {{BASE_URL}}/users
Content-Type: application/json
Accept: application/json
Authorization: {{AUTH_TOKEN}}

### Create Users
POST {{BASE_URL}}/users
Content-Type: application/json
Accept: application/json
Authorization: {{AUTH_TOKEN}}

{
    "first_name": "John",
    "middle_name": "",
    "last_name": "Doe",
    "email": "john.doe@gmail.com",
    "password": "12345",
    "roles": ["Admin"]
}

### Get Single User
GET {{BASE_URL}}/users/1
Content-Type: application/json
Accept: application/json
Authorization: {{AUTH_TOKEN}}

### Update Single User
PUT {{BASE_URL}}/users/1
Content-Type: application/json
Accept: application/json
Authorization: {{AUTH_TOKEN}}

{
    "first_name": "Jane",
    "middle_name": "Testing",
    "last_name": "Doe",
    "email": "jane.doe@gmail.com",
    "roles": ["Admin"]
}

### Delete Single User
DELETE {{BASE_URL}}/users/7
Content-Type: application/json
Accept: application/json
Authorization: {{AUTH_TOKEN}}
